name: Publish release

on:
  push:
    tags:
      - 'flutter_pjsip-v*'

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build-all

      - name: clean working tree
        run: melos clean-working-tree

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./
          retention-days: 1
          compression-level: 2

  publish_github_release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build

      - uses: ./.github/actions/get-flutter

      - name: Create archive with compiled libraries
        run: melos create-lib-archive

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "packages/flutter_pjsip/target/lib.tar.gz"

  # publish_pub_dev_release:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   permissions:
  #     id-token: write # Required for authentication using OIDC

  #   steps:
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: build

  #     - uses: ./.github/actions/get-flutter

  #     - name: Publish to pub.dev
  #       run: melos publish-with-hooks
